export interface Industry {
  slug: string;
  name: string;
  icon: string;
  painPoint: string;
  solution: string;
  /** Alt text for OG image / thumbnail */
  imageAlt: string;
  /** Short meta description (max ~155 chars) */
  metaDescription: string;
  /** SEO keywords */
  keywords: string[];
}

export const industries: Industry[] = [
  {
    slug: 'kedai-kopi',
    name: 'Kedai Kopi & Cafe',
    icon: '☕',
    painPoint: 'Sering kewalahan ngatur stok bahan baku (kopi, susu) dan kasir yang lemot saat jam sibuk.',
    solution: 'Sistem POS super cepat dengan manajemen inventaris resep otomatis, bikin operasional cafe jalan sendiri.',
    imageAlt: 'Sistem kasir digital untuk kedai kopi dan cafe',
    metaDescription: 'Solusi sistem kasir & manajemen stok bahan baku khusus kedai kopi dan cafe. Atasi antrean panjang, waste bahan, dan laporan keuangan manual dengan BisnisRapi.',
    keywords: ['sistem kasir cafe', 'aplikasi kasir kedai kopi', 'manajemen stok cafe', 'software cafe indonesia', 'pos cafe', 'aplikasi kasir untuk kedai kopi', 'sistem kasir coffee shop', 'aplikasi kasir cafe terbaik indonesia'],
  },
  {
    slug: 'toko-baju',
    name: 'Toko Baju & Fashion',
    icon: '👕',
    painPoint: 'Pusing ngurus varian ukuran, warna, dan stok barang mati yang numpuk di gudang.',
    solution: 'Katalog digital terintegrasi kasir, pantau pergerakan tiap varian ukuran & warna secara real-time.',
    imageAlt: 'Sistem kasir digital untuk toko baju dan fashion',
    metaDescription: 'Kelola stok varian ukuran & warna toko baju lebih mudah dengan BisnisRapi. Kurangi barang mati dan tingkatkan penjualan fashion kamu.',
    keywords: ['sistem kasir toko baju', 'aplikasi pos fashion', 'manajemen stok toko pakaian', 'software toko baju indonesia', 'kasir toko fashion', 'sistem kasir untuk toko baju', 'aplikasi kasir untuk konveksi', 'software kasir toko fashion'],
  },
  {
    slug: 'bengkel',
    name: 'Bengkel & Otomotif',
    icon: '🔧',
    painPoint: 'Susah ngelacak riwayat servis pelanggan, stok sparepart tercecer, dan antrean nggak jelas.',
    solution: 'Catatan riwayat servis kendaraan digital, reminder ganti oli otomatis, dan integrasi stok sparepart.',
    imageAlt: 'Aplikasi manajemen bengkel dan servis otomotif',
    metaDescription: 'Kelola bengkel lebih profesional dengan BisnisRapi. Riwayat servis digital, reminder ganti oli, dan stok sparepart terintegrasi dalam satu sistem.',
    keywords: ['aplikasi bengkel', 'sistem manajemen bengkel', 'software bengkel otomotif', 'kasir bengkel', 'aplikasi servis kendaraan', 'sistem pos untuk bengkel', 'aplikasi kasir bengkel motor', 'software manajemen bengkel mobil'],
  },
  {
    slug: 'apotek',
    name: 'Apotek & Klinik',
    icon: '💊',
    painPoint: 'Pusing mantau tanggal kedaluwarsa (expired date) ribuan obat dan stok minimum.',
    solution: 'Sistem POS dengan notifikasi otomatis untuk obat hampir kedaluwarsa & laporan mutasi stok presisi.',
    imageAlt: 'Sistem manajemen stok obat untuk apotek dan klinik',
    metaDescription: 'Kelola stok obat apotek dengan BisnisRapi. Notifikasi expired date otomatis, laporan mutasi stok, dan kasir apotek yang cepat dan akurat.',
    keywords: ['software apotek', 'sistem kasir apotek', 'aplikasi manajemen apotek', 'pos apotek indonesia', 'aplikasi stok obat', 'aplikasi kasir untuk apotek kecil', 'software kasir untuk apotek', 'sistem kasir apotek indonesia'],
  },
  {
    slug: 'minimarket',
    name: 'Minimarket & Retail',
    icon: '🛒',
    painPoint: 'Sering ada selisih uang kas dan barang hilang karena nggak ada pencatatan yang rapi.',
    solution: 'Barcode scanner support, laporan shift otomatis, dan deteksi pergerakan uang kas tanpa celah.',
    imageAlt: 'Sistem kasir minimarket dan toko retail modern',
    metaDescription: 'Solusi kasir minimarket terpercaya dari BisnisRapi. Barcode scanner, laporan shift otomatis, dan kontrol kas harian tanpa selisih.',
    keywords: ['sistem kasir minimarket', 'aplikasi pos retail', 'software minimarket indonesia', 'kasir toko retail', 'manajemen minimarket', 'aplikasi kasir untuk minimarket', 'software minimarket sederhana', 'sistem stok toko retail kecil', 'aplikasi toko kelontong digital'],
  },
  {
    slug: 'salon',
    name: 'Salon & Barbershop',
    icon: '✂️',
    painPoint: 'Jadwal booking tabrakan, ribet hitung komisi kapster, dan susah jaga loyalitas pelanggan.',
    solution: 'Sistem booking online, hitung komisi otomatis tiap kapster, dan database pelanggan buat kirim promo diskon.',
    imageAlt: 'Aplikasi booking dan kasir untuk salon dan barbershop',
    metaDescription: 'Kelola salon & barbershop lebih rapi dengan BisnisRapi. Booking online, komisi kapster otomatis, dan program loyalitas pelanggan dalam satu aplikasi.',
    keywords: ['aplikasi salon', 'sistem booking barbershop', 'software kasir salon', 'manajemen salon indonesia', 'aplikasi barbershop', 'sistem kasir salon dan klinik kecantikan', 'aplikasi kasir salon kecantikan', 'sistem booking salon kasir'],
  },
  {
    slug: 'laundry',
    name: 'Jasa Laundry',
    icon: '🧺',
    painPoint: 'Baju pelanggan tertukar, nota hilang, dan susah melacak cucian udah selesai atau belum.',
    solution: 'Tracking status cucian via WhatsApp, nota digital, dan manajemen rak otomatis.',
    imageAlt: 'Sistem manajemen order untuk jasa laundry',
    metaDescription: 'Kelola jasa laundry tanpa ribet dengan BisnisRapi. Tracking status cucian, nota digital, dan notifikasi WhatsApp otomatis ke pelanggan.',
    keywords: ['aplikasi laundry', 'sistem manajemen laundry', 'software laundry indonesia', 'kasir laundry', 'aplikasi tracking laundry', 'aplikasi kasir untuk laundry', 'sistem tracking laundry digital', 'software manajemen laundry'],
  },
  {
    slug: 'toko-bangunan',
    name: 'Toko Bangunan',
    icon: '🏗️',
    painPoint: 'Hutang pelanggan numpuk susah ditagih dan barang besar susah dicatat stoknya.',
    solution: 'Manajemen piutang pelanggan (kasbon) dengan pengingat tagihan otomatis & laporan aset terkini.',
    imageAlt: 'Sistem kasir dan manajemen piutang toko bangunan',
    metaDescription: 'Atasi kasbon menumpuk di toko bangunan dengan BisnisRapi. Manajemen piutang, pengingat tagihan otomatis, dan stok material bangunan terkontrol.',
    keywords: ['software toko bangunan', 'aplikasi kasir toko material', 'manajemen piutang toko bangunan', 'sistem kasir material bangunan', 'aplikasi toko bangunan'],
  },
  {
    slug: 'distributor',
    name: 'Distributor & Grosir',
    icon: '📦',
    painPoint: 'Tim sales lapangan ribet catat orderan manual, sering salah kirim barang ke agen.',
    solution: 'Aplikasi mobile untuk tim sales, integrasi order langsung ke gudang, dan tier harga grosir otomatis.',
    imageAlt: 'Sistem manajemen distribusi dan penjualan grosir',
    metaDescription: 'Optimalkan distribusi & grosir dengan BisnisRapi. Aplikasi mobile sales, integrasi gudang, dan tier harga otomatis untuk agen dan reseller.',
    keywords: ['software distributor', 'aplikasi sales lapangan', 'sistem manajemen grosir', 'aplikasi distribusi barang', 'software grosir indonesia'],
  },
  {
    slug: 'resto',
    name: 'Restoran & Rumah Makan',
    icon: '🍲',
    painPoint: 'Pesanan di meja sering salah masuk ke dapur, bahan baku banyak terbuang (waste).',
    solution: 'Aplikasi order QR menu di meja, langsung nge-print ke dapur, dan laporan waste bahan baku.',
    imageAlt: 'Sistem POS restoran dengan order QR code dan manajemen dapur',
    metaDescription: 'Tingkatkan efisiensi restoran dengan BisnisRapi. Order QR menu, cetak otomatis ke dapur, dan kontrol waste bahan baku untuk laba maksimal.',
    keywords: ['sistem kasir restoran', 'aplikasi pos rumah makan', 'software restoran indonesia', 'aplikasi order meja restoran', 'manajemen restoran', 'aplikasi kasir untuk warung makan', 'sistem pos untuk warung makan', 'software manajemen restoran kecil'],
  },
  {
    slug: 'petshop',
    name: 'Petshop & Klinik Hewan',
    icon: '🐶',
    painPoint: 'Ribet bedain stok makanan hewan, obat, aksesoris, serta jadwal grooming atau vaksin.',
    solution: 'Pencatatan varian produk super lengkap dan fitur reminder jadwal grooming pelanggan setia.',
    imageAlt: 'Aplikasi manajemen petshop dan klinik hewan',
    metaDescription: 'Kelola petshop & klinik hewan lebih mudah dengan BisnisRapi. Stok produk lengkap, reminder grooming, dan jadwal vaksin hewan peliharaan pelanggan.',
    keywords: ['aplikasi petshop', 'software klinik hewan', 'sistem kasir petshop', 'manajemen petshop indonesia', 'aplikasi grooming hewan'],
  },
  {
    slug: 'toko-elektronik',
    name: 'Toko Elektronik & Gadget',
    icon: '📱',
    painPoint: 'Sering kewalahan ngelacak nomor seri (SN) dan garansi tiap barang yang terjual.',
    solution: 'Fitur input & tracking Serial Number (SN) di setiap struk, gampang cek garansi kapan aja.',
    imageAlt: 'Sistem kasir toko elektronik dengan tracking serial number',
    metaDescription: 'Kelola toko elektronik & gadget dengan BisnisRapi. Tracking serial number, manajemen garansi, dan stok produk elektronik terkontrol rapi.',
    keywords: ['software toko elektronik', 'aplikasi kasir gadget', 'sistem tracking serial number', 'manajemen toko elektronik', 'pos toko gadget'],
  },
  {
    slug: 'bahan-kue',
    name: 'Toko Bahan Kue',
    icon: '🍰',
    painPoint: 'Banyak bahan curah yang harus ditimbang, stok gramasi sering nggak sinkron dengan catatan kasir.',
    solution: 'Dukungan satuan dinamis (gram, kg, ml) dan resep konversi otomatis saat barang terjual.',
    imageAlt: 'Sistem kasir toko bahan kue dengan satuan timbangan',
    metaDescription: 'Kelola toko bahan kue dengan BisnisRapi. Satuan gram, kg, ml terintegrasi kasir, stok bahan curah akurat, dan konversi resep otomatis.',
    keywords: ['aplikasi toko bahan kue', 'software kasir bahan kue', 'sistem stok bahan kue', 'pos toko bahan kue', 'manajemen toko bahan kue'],
  },
  {
    slug: 'frozen-food',
    name: 'Toko Frozen Food',
    icon: '🧊',
    painPoint: 'Stok barang banyak yang mirip, susah ngatur stok minimum biar nggak kehabisan barang fast-moving.',
    solution: 'Peringatan stok menipis otomatis (low-stock alert) dan manajemen barcode produk yang mudah.',
    imageAlt: 'Sistem manajemen stok toko frozen food',
    metaDescription: 'Kelola toko frozen food tanpa kehabisan stok dengan BisnisRapi. Low-stock alert otomatis, barcode scanner, dan laporan produk terlaris.',
    keywords: ['aplikasi toko frozen food', 'software kasir frozen food', 'sistem stok frozen food', 'manajemen toko frozen food', 'pos frozen food'],
  },
  {
    slug: 'kosmetik',
    name: 'Toko Kosmetik & Skincare',
    icon: '💄',
    painPoint: 'Banyak brand dan varian shade, bingung cari barang saat pelanggan tanya ketersediaan.',
    solution: 'Pencarian produk kilat dengan filter kategori & brand, plus integrasi poin member pelanggan.',
    imageAlt: 'Sistem kasir toko kosmetik dan skincare',
    metaDescription: 'Kelola toko kosmetik & skincare dengan BisnisRapi. Pencarian produk cepat, filter brand, dan program poin member untuk pelanggan setia.',
    keywords: ['aplikasi toko kosmetik', 'software kasir skincare', 'sistem pos kosmetik', 'manajemen toko kecantikan', 'kasir toko skincare'],
  },
  {
    slug: 'toko-atk',
    name: 'Toko Buku & Alat Tulis (ATK)',
    icon: '📚',
    painPoint: 'Ribuan item kecil-kecil sering hilang atau lupa input, stok riil dan sistem nggak pernah klop.',
    solution: 'Sistem scan barcode super cepat dan fitur opname stok (stock opname) tanpa harus tutup toko.',
    imageAlt: 'Sistem kasir toko buku dan alat tulis ATK',
    metaDescription: 'Kelola toko buku & ATK dengan BisnisRapi. Scan barcode cepat, stock opname tanpa tutup toko, dan stok ribuan item selalu akurat.',
    keywords: ['aplikasi toko ATK', 'software kasir toko buku', 'sistem stok alat tulis', 'pos toko ATK', 'manajemen toko buku'],
  },
  {
    slug: 'sembako',
    name: 'Grosir Sembako',
    icon: '🍚',
    painPoint: 'Fluktuasi harga modal tiap hari bikin pusing nentuin harga jual grosir dan ecer.',
    solution: 'Update harga massal dalam 1 klik dan sistem tier harga (ecer, grosir, member) otomatis.',
    imageAlt: 'Sistem kasir grosir sembako dengan tier harga otomatis',
    metaDescription: 'Kelola grosir sembako lebih efisien dengan BisnisRapi. Update harga massal, tier harga ecer-grosir otomatis, dan laporan penjualan harian akurat.',
    keywords: ['software grosir sembako', 'aplikasi kasir sembako', 'sistem manajemen sembako', 'pos grosir sembako', 'aplikasi toko sembako', 'software kasir untuk toko kelontong', 'aplikasi pencatatan penjualan untuk warung', 'sistem kasir toko sembako'],
  },
  {
    slug: 'konter-pulsa',
    name: 'Konter Pulsa & Aksesoris',
    icon: '⚡',
    painPoint: 'Uang fisik dari jual pulsa dan aksesoris sering campur, laba harian susah dihitung.',
    solution: 'Pemisahan laporan kas penjualan fisik dan digital, ketahuan untung bersih tiap hari.',
    imageAlt: 'Sistem kasir konter pulsa dan aksesoris handphone',
    metaDescription: 'Kelola konter pulsa & aksesoris dengan BisnisRapi. Pisahkan laporan penjualan fisik dan digital, hitung laba bersih harian secara otomatis.',
    keywords: ['aplikasi konter pulsa', 'software kasir konter hp', 'sistem manajemen konter pulsa', 'pos konter pulsa', 'aplikasi jualan pulsa'],
  },
  {
    slug: 'baby-shop',
    name: 'Toko Perlengkapan Bayi',
    icon: '🍼',
    painPoint: 'Sering kasih diskon manual ke ibu-ibu langganan, laba malah jadi minus tanpa sadar.',
    solution: 'Sistem program loyalitas (member) otomatis diskon tanpa harus input manual tiap transaksi.',
    imageAlt: 'Sistem kasir toko perlengkapan bayi dengan program member',
    metaDescription: 'Kelola toko perlengkapan bayi dengan BisnisRapi. Program member otomatis, diskon terkontrol, dan stok produk bayi selalu rapi dan akurat.',
    keywords: ['aplikasi toko bayi', 'software kasir baby shop', 'sistem manajemen toko bayi', 'pos baby shop', 'aplikasi perlengkapan bayi'],
  },
  {
    slug: 'toko-sepeda',
    name: 'Toko & Servis Sepeda',
    icon: '🚲',
    painPoint: 'Campur aduk antara penjualan part, unit sepeda, dan ongkos jasa servis mekanik.',
    solution: 'Sistem pisah item barang dan jasa, gampang bagi hasil atau komisi untuk mekanik.',
    imageAlt: 'Sistem kasir toko sepeda dan jasa servis',
    metaDescription: 'Kelola toko & servis sepeda dengan BisnisRapi. Pisahkan penjualan part, unit, dan jasa servis, serta hitung komisi mekanik secara otomatis.',
    keywords: ['aplikasi toko sepeda', 'software kasir servis sepeda', 'sistem manajemen toko sepeda', 'pos toko sepeda', 'aplikasi bengkel sepeda'],
  },
  {
    slug: 'optik',
    name: 'Optik Kacamata',
    icon: '👓',
    painPoint: 'Data resep mata pelanggan sering hilang karena dicatat di buku manual.',
    solution: 'Simpan resep mata (minus, silinder) langsung di profil pelanggan, next order tinggal panggil data.',
    imageAlt: 'Sistem manajemen optik kacamata dengan database resep mata',
    metaDescription: 'Kelola optik kacamata lebih profesional dengan BisnisRapi. Simpan resep mata pelanggan digital, stok frame & lensa terkontrol, dan kasir cepat.',
    keywords: ['software optik kacamata', 'aplikasi kasir optik', 'sistem manajemen optik', 'pos optik indonesia', 'aplikasi toko kacamata'],
  },
  {
    slug: 'florist',
    name: 'Florist (Toko Bunga)',
    icon: '💐',
    painPoint: 'Terima order custom, DP masuk, tapi lupa jadwal kirim atau salah alamat penerima.',
    solution: 'Manajemen pesanan custom (Pre-order), pencatatan DP, dan reminder jadwal pengiriman.',
    imageAlt: 'Sistem manajemen order dan pengiriman untuk florist toko bunga',
    metaDescription: 'Kelola florist & toko bunga dengan BisnisRapi. Manajemen pre-order, pencatatan DP, dan reminder jadwal pengiriman bunga otomatis.',
    keywords: ['aplikasi florist', 'software toko bunga', 'sistem manajemen florist', 'kasir toko bunga', 'aplikasi order bunga'],
  },
  {
    slug: 'toko-emas',
    name: 'Toko Perhiasan & Emas',
    icon: '💍',
    painPoint: 'Harga emas naik turun tiap jam, capek ngubah harga di setiap display produk.',
    solution: 'Fitur harga fluktuatif berdasarkan persentase atau harga dasar pasaran saat itu juga.',
    imageAlt: 'Sistem kasir toko perhiasan dan emas dengan harga dinamis',
    metaDescription: 'Kelola toko emas & perhiasan dengan BisnisRapi. Harga fluktuatif otomatis, stok perhiasan terkontrol, dan laporan penjualan emas akurat.',
    keywords: ['software toko emas', 'aplikasi kasir perhiasan', 'sistem manajemen toko emas', 'pos toko perhiasan', 'aplikasi toko emas indonesia'],
  },
  {
    slug: 'car-wash',
    name: 'Cuci Mobil & Motor',
    icon: '🚗',
    painPoint: 'Mobil yang masuk antrean suka terlewat, ngeribetin kalau lagi ramai di akhir pekan.',
    solution: 'Sistem antrean digital berdasarkan pelat nomor kendaraan, dan struk antrean otomatis.',
    imageAlt: 'Sistem antrean digital untuk cuci mobil dan motor',
    metaDescription: 'Kelola cuci mobil & motor lebih tertib dengan BisnisRapi. Antrean digital by plat nomor, struk otomatis, dan laporan pendapatan harian.',
    keywords: ['aplikasi cuci mobil', 'software manajemen car wash', 'sistem antrean cuci motor', 'kasir car wash', 'aplikasi bengkel cuci kendaraan'],
  },
  {
    slug: 'gym-fitness',
    name: 'Gym & Studio Fitness',
    icon: '🏋️',
    painPoint: 'Ribet mantau masa aktif membership anggota dan jualan suplemen secara terpisah.',
    solution: 'Satu sistem untuk kelola masa aktif member, akses masuk, dan POS kantin/suplemen.',
    imageAlt: 'Sistem manajemen membership gym dan studio fitness',
    metaDescription: 'Kelola gym & studio fitness dengan BisnisRapi. Manajemen membership, kontrol akses, dan POS suplemen dalam satu sistem terintegrasi.',
    keywords: ['software gym', 'aplikasi manajemen fitness center', 'sistem membership gym', 'kasir gym indonesia', 'aplikasi studio fitness'],
  },
  {
    slug: 'percetakan',
    name: 'Digital Printing & Fotocopy',
    icon: '🖨️',
    painPoint: 'Banyak order file masuk, DP belum lunas, hasil cetakan diambil orang lain.',
    solution: 'Nota digital tracking progres cetak, pencatatan termin pembayaran (DP & Pelunasan).',
    imageAlt: 'Sistem manajemen order untuk digital printing dan fotocopy',
    metaDescription: 'Kelola usaha digital printing & fotocopy dengan BisnisRapi. Tracking order cetak, pencatatan DP & pelunasan, dan nota digital pelanggan.',
    keywords: ['software percetakan', 'aplikasi digital printing', 'sistem manajemen fotocopy', 'kasir percetakan', 'aplikasi order cetak'],
  },
  {
    slug: 'toko-buah',
    name: 'Toko Buah Segar',
    icon: '🍎',
    painPoint: 'Susah mantau buah mana yang udah mau busuk biar bisa cepat didiskon (clearance).',
    solution: 'Manajemen masa simpan produk dan promo bundling otomatis untuk produk hampir layu.',
    imageAlt: 'Sistem kasir toko buah segar dengan manajemen masa simpan',
    metaDescription: 'Kelola toko buah segar dengan BisnisRapi. Pantau masa simpan buah, promo clearance otomatis, dan stok produk segar selalu terkontrol.',
    keywords: ['aplikasi toko buah', 'software kasir buah segar', 'sistem manajemen toko buah', 'pos toko buah', 'aplikasi jualan buah'],
  },
  {
    slug: 'toko-pancing',
    name: 'Toko Alat Pancing',
    icon: '🎣',
    painPoint: 'Barang printilan kecil (kail, pelampung) sering hilang, susah di-track manual.',
    solution: 'Stok opname super gampang dengan scan barcode via HP, cocok buat item-item kecil.',
    imageAlt: 'Sistem kasir toko alat pancing dengan barcode scanner',
    metaDescription: 'Kelola toko alat pancing dengan BisnisRapi. Scan barcode via HP, stok opname mudah, dan ribuan item kecil selalu tercatat akurat.',
    keywords: ['aplikasi toko pancing', 'software kasir alat pancing', 'sistem stok toko pancing', 'pos toko pancing', 'manajemen toko alat pancing'],
  },
  {
    slug: 'studio-foto',
    name: 'Studio Fotografi',
    icon: '📸',
    painPoint: 'Jadwal sesi foto bentrok, bingung ngatur paket foto + cetak pigura.',
    solution: 'Kalender booking terintegrasi dan sistem invoice otomatis lengkap dengan paket custom.',
    imageAlt: 'Sistem booking dan manajemen studio fotografi',
    metaDescription: 'Kelola studio fotografi lebih profesional dengan BisnisRapi. Booking kalender, invoice paket foto otomatis, dan manajemen sesi pemotretan.',
    keywords: ['aplikasi studio foto', 'software booking studio fotografi', 'sistem manajemen studio foto', 'kasir studio foto', 'aplikasi fotografi indonesia'],
  },
  {
    slug: 'toko-daging',
    name: 'Meat Shop & Toko Daging',
    icon: '🥩',
    painPoint: 'Sisa potongan daging (trimming) bingung dicatat sebagai stok apa, malah bikin rugi.',
    solution: 'Fitur konversi produk turunan (daging utuh ke slice/mince) dengan HPP otomatis menyesuaikan.',
    imageAlt: 'Sistem kasir meat shop dan toko daging segar',
    metaDescription: 'Kelola meat shop & toko daging dengan BisnisRapi. Konversi produk turunan otomatis, HPP akurat, dan stok daging segar terkontrol setiap hari.',
    keywords: ['aplikasi toko daging', 'software kasir meat shop', 'sistem manajemen toko daging', 'pos toko daging', 'aplikasi jualan daging'],
  },
  {
    slug: 'klinik-gigi',
    name: 'Klinik Dokter Gigi',
    icon: '🦷',
    painPoint: 'Pasien sering lupa jadwal kontrol, riwayat rekam medis berantakan di map kertas.',
    solution: 'Digitalisasi rekam medis pasien terintegrasi dengan reminder WhatsApp otomatis jadwal kontrol.',
    imageAlt: 'Sistem manajemen rekam medis klinik dokter gigi',
    metaDescription: 'Kelola klinik gigi lebih modern dengan BisnisRapi. Rekam medis digital, reminder jadwal kontrol WhatsApp, dan manajemen pasien terpusat.',
    keywords: ['software klinik gigi', 'aplikasi manajemen klinik gigi', 'sistem rekam medis gigi', 'kasir klinik gigi', 'aplikasi dokter gigi', 'sistem kasir klinik gigi', 'software klinik gigi sederhana', 'aplikasi manajemen pasien klinik kecil'],
  },
  {
    slug: 'toko-sepatu',
    name: 'Toko Sepatu & Tas',
    icon: '👟',
    painPoint: 'Punya banyak cabang, bingung mutasi stok sepatu kalau di toko A habis tapi di toko B numpuk.',
    solution: 'Sistem multi-cabang terpusat, gampang request mutasi antar toko dalam hitungan detik.',
    imageAlt: 'Sistem kasir multi-cabang toko sepatu dan tas',
    metaDescription: 'Kelola toko sepatu & tas multi-cabang dengan BisnisRapi. Mutasi stok antar toko mudah, pantau penjualan semua cabang dari satu dashboard.',
    keywords: ['software toko sepatu', 'aplikasi kasir toko tas', 'sistem multi-cabang toko sepatu', 'pos toko sepatu', 'manajemen toko sepatu indonesia'],
  },
  {
    slug: 'toko-oleh-oleh',
    name: 'Pusat Oleh-oleh',
    icon: '🎁',
    painPoint: 'Jam sibuk rombongan bus datang, kasir kewalahan input, antrean mengular panjang.',
    solution: 'Kasir mode cepat dengan shortcut tombol, transaksi nggak sampai 10 detik per pelanggan.',
    imageAlt: 'Sistem kasir cepat untuk pusat oleh-oleh wisata',
    metaDescription: 'Kelola pusat oleh-oleh lebih lancar dengan BisnisRapi. Kasir super cepat, shortcut produk, dan laporan penjualan harian untuk toko wisata.',
    keywords: ['aplikasi toko oleh-oleh', 'software kasir pusat oleh-oleh', 'sistem pos toko wisata', 'kasir oleh-oleh', 'manajemen toko oleh-oleh'],
  },
  {
    slug: 'klinik-kecantikan',
    name: 'Klinik Kecantikan',
    icon: '✨',
    painPoint: 'Sulit melacak pemakaian bahan treatment krim oleh dokter dan penjualan produk skincare.',
    solution: 'Pemotongan stok bahan otomatis tiap tindakan treatment (BOM) & rekap komisi dokter presisi.',
    imageAlt: 'Sistem manajemen klinik kecantikan dan treatment skincare',
    metaDescription: 'Kelola klinik kecantikan dengan BisnisRapi. Stok bahan treatment terpotong otomatis, komisi dokter akurat, dan penjualan produk skincare tercatat rapi.',
    keywords: ['software klinik kecantikan', 'aplikasi manajemen klinik estetik', 'sistem kasir klinik kecantikan', 'pos klinik kecantikan', 'aplikasi klinik estetika'],
  },
  {
    slug: 'rental-kendaraan',
    name: 'Rental Mobil & Motor',
    icon: '🚙',
    painPoint: 'Susah melacak unit kendaraan mana yang lagi disewa, kapan balik, dan denda keterlambatan.',
    solution: 'Sistem ketersediaan kalender unit, pencatatan deposit uang, dan denda perpanjangan otomatis.',
    imageAlt: 'Sistem manajemen rental mobil dan motor',
    metaDescription: 'Kelola rental mobil & motor dengan BisnisRapi. Kalender ketersediaan unit, pencatatan deposit, dan denda keterlambatan otomatis dalam satu sistem.',
    keywords: ['software rental mobil', 'aplikasi manajemen rental kendaraan', 'sistem booking rental motor', 'kasir rental mobil', 'aplikasi rental kendaraan'],
  },
  {
    slug: 'katering',
    name: 'Katering & Warteg',
    icon: '🍱',
    painPoint: 'Sering keliru hitung kebutuhan bahan belanja mentah dari orderan katering harian yang masuk.',
    solution: 'Kalkulator kebutuhan belanja bahan baku otomatis berdasarkan jumlah pesanan porsi harian.',
    imageAlt: 'Sistem manajemen order dan bahan baku katering',
    metaDescription: 'Kelola katering & warteg lebih efisien dengan BisnisRapi. Kalkulator bahan baku otomatis, manajemen order harian, dan laporan laba katering.',
    keywords: ['software katering', 'aplikasi manajemen katering', 'sistem order katering', 'kasir warteg', 'aplikasi katering nasi box'],
  },
  {
    slug: 'toko-kaca',
    name: 'Toko Kaca & Aluminium',
    icon: '🪟',
    painPoint: 'Menghitung harga kaca berdasarkan ukuran (P x L) secara manual rentan salah hitung.',
    solution: 'Fitur input ukuran meter persegi (m2) di kasir yang otomatis menghitung total harga.',
    imageAlt: 'Sistem kasir toko kaca dan aluminium dengan hitung m2',
    metaDescription: 'Kelola toko kaca & aluminium dengan BisnisRapi. Hitung harga per m2 otomatis, stok material terkontrol, dan invoice pelanggan profesional.',
    keywords: ['software toko kaca', 'aplikasi kasir toko aluminium', 'sistem manajemen toko kaca', 'pos toko kaca aluminium', 'aplikasi toko kaca indonesia'],
  },
  {
    slug: 'toko-mainan',
    name: 'Toko Mainan Anak',
    icon: '🧸',
    painPoint: 'Harga beda-beda tiap pelanggan tergantung nawar, susah menetapkan harga pas.',
    solution: 'Sistem limit diskon kasir, biar karyawan nggak sembarangan kasih harga terlalu murah.',
    imageAlt: 'Sistem kasir toko mainan anak dengan kontrol diskon',
    metaDescription: 'Kelola toko mainan anak dengan BisnisRapi. Kontrol diskon kasir, stok mainan terkontrol, dan laporan penjualan harian yang akurat.',
    keywords: ['aplikasi toko mainan', 'software kasir toko mainan anak', 'sistem manajemen toko mainan', 'pos toko mainan', 'kasir toko mainan'],
  },
  {
    slug: 'toko-plastik',
    name: 'Toko Plastik & Kemasan',
    icon: '🛍️',
    painPoint: 'Jual barang dalam hitungan pak, slop, dan ecer bikin bingung nentuin modal dasar (HPP).',
    solution: 'Sistem multi-satuan (PCS, PACK, KARTON) dengan HPP yang menyesuaikan konversi otomatis.',
    imageAlt: 'Sistem kasir toko plastik dan kemasan dengan multi-satuan',
    metaDescription: 'Kelola toko plastik & kemasan dengan BisnisRapi. Multi-satuan PCS, PACK, KARTON otomatis, HPP akurat, dan stok kemasan selalu terkontrol.',
    keywords: ['software toko plastik', 'aplikasi kasir toko kemasan', 'sistem manajemen toko plastik', 'pos toko kemasan', 'aplikasi toko plastik indonesia'],
  },
  {
    slug: 'warung-makan',
    name: 'Warung Makan & Depot',
    icon: '🍜',
    painPoint: 'Susah ngitung laba harian karena semua transaksi dicatat di buku tulis yang gampang hilang.',
    solution: 'Kasir digital sederhana yang bisa dipakai tanpa internet, laporan laba langsung ketahuan tiap hari.',
    imageAlt: 'Sistem kasir digital untuk warung makan dan depot',
    metaDescription: 'Kelola warung makan & depot dengan BisnisRapi. Kasir digital mudah, laporan laba harian otomatis, dan stok bahan makanan terkontrol.',
    keywords: ['aplikasi kasir warung makan', 'software warung makan', 'sistem pos depot makan', 'kasir warung sederhana', 'aplikasi warung makan indonesia'],
  },
  {
    slug: 'toko-herbal',
    name: 'Toko Herbal & Jamu',
    icon: '🌿',
    painPoint: 'Banyak produk herbal dengan nama mirip, sering salah ambil barang dan stok kacau.',
    solution: 'Pencarian produk dengan kode SKU dan deskripsi lengkap, stok herbal selalu akurat.',
    imageAlt: 'Sistem kasir toko herbal dan jamu tradisional',
    metaDescription: 'Kelola toko herbal & jamu dengan BisnisRapi. Pencarian produk akurat, stok herbal terkontrol, dan laporan penjualan produk kesehatan alami.',
    keywords: ['aplikasi toko herbal', 'software kasir toko jamu', 'sistem manajemen toko herbal', 'pos toko herbal', 'kasir toko jamu indonesia'],
  },
  {
    slug: 'toko-pupuk',
    name: 'Toko Pertanian & Pupuk',
    icon: '🌾',
    painPoint: 'Petani langganan sering beli kredit, susah ngontrol siapa yang belum bayar dan berapa.',
    solution: 'Manajemen kasbon petani dengan laporan piutang per pelanggan dan pengingat tagihan otomatis.',
    imageAlt: 'Sistem kasir toko pertanian dan pupuk dengan manajemen kredit',
    metaDescription: 'Kelola toko pertanian & pupuk dengan BisnisRapi. Manajemen kredit petani, stok pupuk & pestisida terkontrol, dan laporan piutang akurat.',
    keywords: ['software toko pertanian', 'aplikasi kasir toko pupuk', 'sistem manajemen toko pertanian', 'pos toko pupuk', 'aplikasi toko agro'],
  },
  {
    slug: 'toko-hewan',
    name: 'Toko Pakan Ternak',
    icon: '🐄',
    painPoint: 'Pakan ternak dijual dalam karung besar, susah ngitung stok sisa dan HPP per kilogram.',
    solution: 'Sistem multi-satuan karung dan kg terintegrasi, HPP per satuan terhitung otomatis.',
    imageAlt: 'Sistem kasir toko pakan ternak dengan multi-satuan',
    metaDescription: 'Kelola toko pakan ternak dengan BisnisRapi. Multi-satuan karung & kg, HPP otomatis, dan stok pakan ternak selalu terpantau akurat.',
    keywords: ['aplikasi toko pakan ternak', 'software kasir pakan hewan', 'sistem manajemen toko ternak', 'pos toko pakan', 'kasir toko pakan ternak'],
  },
  {
    slug: 'koperasi',
    name: 'Koperasi Simpan Pinjam',
    icon: '🏦',
    painPoint: 'Pencatatan simpanan dan pinjaman anggota masih manual di buku besar, rawan salah hitung.',
    solution: 'Sistem pencatatan transaksi simpan pinjam digital dengan laporan saldo anggota real-time.',
    imageAlt: 'Sistem manajemen koperasi simpan pinjam digital',
    metaDescription: 'Kelola koperasi simpan pinjam dengan BisnisRapi. Pencatatan simpanan & pinjaman digital, laporan saldo anggota, dan rekap keuangan koperasi akurat.',
    keywords: ['software koperasi', 'aplikasi simpan pinjam koperasi', 'sistem manajemen koperasi', 'aplikasi koperasi indonesia', 'software koperasi simpan pinjam'],
  },
  {
    slug: 'travel-agent',
    name: 'Agen Travel & Tiket',
    icon: '✈️',
    painPoint: 'Banyak transaksi tiket dan paket wisata, susah ngontrol mana yang sudah lunas atau belum.',
    solution: 'Manajemen invoice paket wisata, tracking status pembayaran, dan laporan komisi agen otomatis.',
    imageAlt: 'Sistem manajemen agen travel dan penjualan tiket',
    metaDescription: 'Kelola agen travel & tiket dengan BisnisRapi. Invoice paket wisata, tracking pembayaran, dan laporan komisi agen perjalanan secara otomatis.',
    keywords: ['software agen travel', 'aplikasi manajemen travel agent', 'sistem kasir agen tiket', 'pos travel agent', 'aplikasi agen perjalanan'],
  },
  {
    slug: 'ekspedisi',
    name: 'Jasa Ekspedisi & Kurir',
    icon: '🚚',
    painPoint: 'Susah melacak paket mana yang sudah dikirim, belum, atau dikembalikan (retur).',
    solution: 'Sistem tracking resi digital, manajemen status pengiriman, dan laporan retur otomatis.',
    imageAlt: 'Sistem manajemen pengiriman jasa ekspedisi dan kurir',
    metaDescription: 'Kelola jasa ekspedisi & kurir dengan BisnisRapi. Tracking resi digital, status pengiriman real-time, dan laporan retur paket otomatis.',
    keywords: ['software ekspedisi', 'aplikasi manajemen kurir', 'sistem tracking pengiriman', 'pos jasa ekspedisi', 'aplikasi kurir lokal'],
  },
  {
    slug: 'toko-cat',
    name: 'Toko Cat & Dekorasi',
    icon: '🎨',
    painPoint: 'Ribuan kode warna cat bikin bingung, stok sering nggak sinkron antara display dan gudang.',
    solution: 'Pencarian produk by kode warna, manajemen stok per varian, dan laporan produk terlaris.',
    imageAlt: 'Sistem kasir toko cat dan dekorasi interior',
    metaDescription: 'Kelola toko cat & dekorasi dengan BisnisRapi. Pencarian kode warna cepat, stok varian cat terkontrol, dan laporan penjualan produk dekorasi.',
    keywords: ['software toko cat', 'aplikasi kasir toko cat', 'sistem manajemen toko cat', 'pos toko cat dekorasi', 'kasir toko cat indonesia'],
  },
  {
    slug: 'toko-listrik',
    name: 'Toko Material Listrik',
    icon: '🔌',
    painPoint: 'Ribuan item kabel, saklar, dan komponen listrik susah dicatat stoknya secara manual.',
    solution: 'Barcode scanner untuk ribuan SKU, stok opname digital, dan laporan barang fast-moving.',
    imageAlt: 'Sistem kasir toko material listrik dan komponen elektrikal',
    metaDescription: 'Kelola toko material listrik dengan BisnisRapi. Barcode scanner, stok ribuan komponen listrik akurat, dan laporan penjualan material elektrikal.',
    keywords: ['software toko listrik', 'aplikasi kasir material listrik', 'sistem manajemen toko elektrikal', 'pos toko listrik', 'kasir toko material listrik'],
  },
  {
    slug: 'toko-obat-hewan',
    name: 'Toko Obat & Pakan Hewan',
    icon: '🐾',
    painPoint: 'Obat hewan punya tanggal kedaluwarsa, sering lupa cek dan malah jual produk expired.',
    solution: 'Notifikasi otomatis produk mendekati expired dan manajemen stok FIFO untuk obat hewan.',
    imageAlt: 'Sistem kasir toko obat dan pakan hewan dengan manajemen expired',
    metaDescription: 'Kelola toko obat & pakan hewan dengan BisnisRapi. Notifikasi expired otomatis, stok FIFO, dan manajemen produk hewan peliharaan terkontrol.',
    keywords: ['aplikasi toko obat hewan', 'software kasir pakan hewan', 'sistem manajemen toko hewan', 'pos toko obat hewan', 'kasir toko pakan hewan'],
  },
  {
    slug: 'kursus',
    name: 'Lembaga Kursus & Les Privat',
    icon: '📖',
    painPoint: 'Susah ngontrol jadwal siswa, pembayaran SPP sering telat, dan absensi masih manual.',
    solution: 'Manajemen jadwal kelas, tagihan SPP otomatis, dan absensi digital terintegrasi per siswa.',
    imageAlt: 'Sistem manajemen lembaga kursus dan les privat',
    metaDescription: 'Kelola lembaga kursus & les privat dengan BisnisRapi. Jadwal kelas digital, tagihan SPP otomatis, dan absensi siswa terpantau real-time.',
    keywords: ['software lembaga kursus', 'aplikasi manajemen les privat', 'sistem administrasi kursus', 'aplikasi kursus indonesia', 'software les privat'],
  },
  {
    slug: 'toko-sport',
    name: 'Toko Perlengkapan Olahraga',
    icon: '🏅',
    painPoint: 'Banyak varian ukuran jersey, sepatu, dan alat olahraga bikin stok sering kacau.',
    solution: 'Manajemen varian ukuran dan warna terintegrasi, pantau stok tiap SKU secara real-time.',
    imageAlt: 'Sistem kasir toko perlengkapan olahraga dan sport',
    metaDescription: 'Kelola toko perlengkapan olahraga dengan BisnisRapi. Manajemen varian ukuran & warna, stok sport equipment terkontrol, dan kasir cepat.',
    keywords: ['software toko olahraga', 'aplikasi kasir toko sport', 'sistem manajemen toko olahraga', 'pos toko sport', 'kasir toko perlengkapan olahraga'],
  },
  {
    slug: 'toko-musik',
    name: 'Toko Alat Musik',
    icon: '🎸',
    painPoint: 'Alat musik mahal susah dicatat stoknya, sering ada yang hilang atau salah harga jual.',
    solution: 'Tracking stok per serial number alat musik, harga jual terkontrol, dan laporan aset akurat.',
    imageAlt: 'Sistem kasir toko alat musik dengan tracking serial number',
    metaDescription: 'Kelola toko alat musik dengan BisnisRapi. Tracking serial number, stok instrumen terkontrol, dan laporan penjualan alat musik akurat.',
    keywords: ['software toko alat musik', 'aplikasi kasir toko musik', 'sistem manajemen toko musik', 'pos toko alat musik', 'kasir toko musik indonesia'],
  },
  {
    slug: 'toko-komputer',
    name: 'Toko Komputer & Laptop',
    icon: '💻',
    painPoint: 'Laptop dan komponen punya nomor seri, susah ngelacak garansi dan riwayat penjualan.',
    solution: 'Input serial number wajib di setiap transaksi, cek garansi dan riwayat servis dalam detik.',
    imageAlt: 'Sistem kasir toko komputer dan laptop dengan tracking garansi',
    metaDescription: 'Kelola toko komputer & laptop dengan BisnisRapi. Tracking serial number & garansi, stok komponen terkontrol, dan laporan penjualan akurat.',
    keywords: ['software toko komputer', 'aplikasi kasir toko laptop', 'sistem manajemen toko komputer', 'pos toko laptop', 'kasir toko komputer indonesia'],
  },
  {
    slug: 'toko-hp',
    name: 'Toko HP & Servis Handphone',
    icon: '📲',
    painPoint: 'IMEI HP sering nggak dicatat, susah buktiin kalau ada klaim garansi atau barang hilang.',
    solution: 'Wajib input IMEI di setiap transaksi jual-beli, riwayat HP terlacak sampai ke pembeli.',
    imageAlt: 'Sistem kasir toko HP dan servis handphone dengan tracking IMEI',
    metaDescription: 'Kelola toko HP & servis handphone dengan BisnisRapi. Tracking IMEI, manajemen garansi, dan stok HP terkontrol untuk toko ponsel profesional.',
    keywords: ['software toko HP', 'aplikasi kasir toko handphone', 'sistem manajemen toko ponsel', 'pos toko HP', 'kasir servis handphone'],
  },
  {
    slug: 'toko-furnitur',
    name: 'Toko Furnitur & Mebel',
    icon: '🪑',
    painPoint: 'Barang furnitur besar susah dicatat stoknya, sering ada pesanan indent yang lupa difollow-up.',
    solution: 'Manajemen pesanan indent (pre-order), tracking status produksi, dan pengingat pengiriman otomatis.',
    imageAlt: 'Sistem manajemen toko furnitur dan mebel dengan pre-order',
    metaDescription: 'Kelola toko furnitur & mebel dengan BisnisRapi. Manajemen indent, tracking produksi, dan pengingat pengiriman furnitur otomatis ke pelanggan.',
    keywords: ['software toko furnitur', 'aplikasi kasir toko mebel', 'sistem manajemen toko furnitur', 'pos toko mebel', 'kasir toko furnitur indonesia'],
  },
  {
    slug: 'toko-karpet',
    name: 'Toko Karpet & Gordyn',
    icon: '🏠',
    painPoint: 'Karpet dan gordyn dijual per meter, susah ngitung harga dan stok sisa gulungan.',
    solution: 'Fitur penjualan per meter dengan kalkulasi harga otomatis dan sisa stok gulungan akurat.',
    imageAlt: 'Sistem kasir toko karpet dan gordyn dengan penjualan per meter',
    metaDescription: 'Kelola toko karpet & gordyn dengan BisnisRapi. Penjualan per meter otomatis, stok gulungan terkontrol, dan invoice pelanggan profesional.',
    keywords: ['software toko karpet', 'aplikasi kasir toko gordyn', 'sistem manajemen toko karpet', 'pos toko karpet', 'kasir toko gordyn indonesia'],
  },
  {
    slug: 'toko-tanaman',
    name: 'Toko Tanaman Hias',
    icon: '🌺',
    painPoint: 'Tanaman hias punya harga fluktuatif dan stok berubah cepat, susah update manual tiap hari.',
    solution: 'Update harga dan stok tanaman cepat via mobile, laporan tanaman terlaris per periode.',
    imageAlt: 'Sistem kasir toko tanaman hias dengan manajemen stok',
    metaDescription: 'Kelola toko tanaman hias dengan BisnisRapi. Update harga & stok cepat, laporan tanaman terlaris, dan manajemen penjualan tanaman hias mudah.',
    keywords: ['aplikasi toko tanaman hias', 'software kasir toko tanaman', 'sistem manajemen toko tanaman', 'pos toko tanaman hias', 'kasir toko bunga tanaman'],
  },
  {
    slug: 'toko-aquarium',
    name: 'Toko Aquarium & Ikan Hias',
    icon: '🐠',
    painPoint: 'Ikan hias punya harga beda-beda per ekor, susah ngitung stok yang terus berubah.',
    solution: 'Manajemen stok per ekor dengan harga satuan fleksibel dan laporan penjualan ikan hias.',
    imageAlt: 'Sistem kasir toko aquarium dan ikan hias',
    metaDescription: 'Kelola toko aquarium & ikan hias dengan BisnisRapi. Stok per ekor, harga satuan fleksibel, dan laporan penjualan ikan hias akurat.',
    keywords: ['aplikasi toko aquarium', 'software kasir toko ikan hias', 'sistem manajemen toko aquarium', 'pos toko ikan hias', 'kasir toko aquarium'],
  },
  {
    slug: 'toko-parfum',
    name: 'Toko Parfum & Wewangian',
    icon: '🌸',
    painPoint: 'Banyak varian aroma dan ukuran botol, stok sering kacau dan pelanggan nggak bisa cari produk.',
    solution: 'Katalog produk dengan filter aroma dan ukuran, stok per varian terpantau real-time.',
    imageAlt: 'Sistem kasir toko parfum dan wewangian dengan katalog digital',
    metaDescription: 'Kelola toko parfum & wewangian dengan BisnisRapi. Katalog digital per aroma & ukuran, stok terkontrol, dan program member pelanggan setia.',
    keywords: ['software toko parfum', 'aplikasi kasir toko wewangian', 'sistem manajemen toko parfum', 'pos toko parfum', 'kasir toko parfum indonesia'],
  },
  {
    slug: 'toko-jam',
    name: 'Toko Jam Tangan',
    icon: '🕐',
    painPoint: 'Jam tangan mahal susah dicatat garansinya, sering ada klaim garansi yang nggak bisa diverifikasi.',
    solution: 'Tracking serial number dan kartu garansi digital per unit, verifikasi garansi dalam detik.',
    imageAlt: 'Sistem kasir toko jam tangan dengan tracking garansi',
    metaDescription: 'Kelola toko jam tangan dengan BisnisRapi. Tracking serial number & garansi digital, stok jam terkontrol, dan laporan penjualan akurat.',
    keywords: ['software toko jam tangan', 'aplikasi kasir toko jam', 'sistem manajemen toko jam', 'pos toko jam tangan', 'kasir toko jam indonesia'],
  },
  {
    slug: 'toko-kamera',
    name: 'Toko Kamera & Aksesoris',
    icon: '📷',
    painPoint: 'Kamera dan lensa punya serial number, susah ngelacak unit yang disewa atau dijual.',
    solution: 'Tracking serial number kamera dan lensa, manajemen rental unit, dan laporan aset akurat.',
    imageAlt: 'Sistem kasir toko kamera dan aksesoris fotografi',
    metaDescription: 'Kelola toko kamera & aksesoris dengan BisnisRapi. Tracking serial number, manajemen rental kamera, dan stok aksesoris fotografi terkontrol.',
    keywords: ['software toko kamera', 'aplikasi kasir toko kamera', 'sistem manajemen toko kamera', 'pos toko kamera', 'kasir toko kamera indonesia'],
  },
  {
    slug: 'toko-drone',
    name: 'Toko Drone & Elektronik Hobby',
    icon: '🚁',
    painPoint: 'Spare part drone kecil-kecil dan mahal, sering hilang atau salah jual ke pelanggan.',
    solution: 'Manajemen stok komponen drone per SKU, tracking serial unit, dan laporan penjualan akurat.',
    imageAlt: 'Sistem kasir toko drone dan elektronik hobby',
    metaDescription: 'Kelola toko drone & elektronik hobby dengan BisnisRapi. Stok komponen per SKU, tracking serial number, dan manajemen penjualan drone profesional.',
    keywords: ['software toko drone', 'aplikasi kasir toko drone', 'sistem manajemen toko drone', 'pos toko drone', 'kasir toko elektronik hobby'],
  },
  {
    slug: 'toko-gaming',
    name: 'Toko Gaming & Konsol',
    icon: '🎮',
    painPoint: 'Konsol dan game bekas susah ditentukan harganya, sering rugi karena salah hitung HPP.',
    solution: 'Manajemen produk baru dan bekas terpisah, HPP otomatis, dan tracking serial konsol.',
    imageAlt: 'Sistem kasir toko gaming dan konsol game',
    metaDescription: 'Kelola toko gaming & konsol dengan BisnisRapi. Manajemen produk baru & bekas, tracking serial konsol, dan HPP otomatis untuk laba maksimal.',
    keywords: ['software toko gaming', 'aplikasi kasir toko game', 'sistem manajemen toko konsol', 'pos toko gaming', 'kasir toko game indonesia'],
  },
  {
    slug: 'toko-buku-bekas',
    name: 'Toko Buku Bekas',
    icon: '📕',
    painPoint: 'Setiap buku bekas punya harga beda, susah input manual satu per satu dan sering salah harga.',
    solution: 'Input harga per item fleksibel dengan barcode ISBN, pencarian judul cepat, dan laporan stok.',
    imageAlt: 'Sistem kasir toko buku bekas dengan barcode ISBN',
    metaDescription: 'Kelola toko buku bekas dengan BisnisRapi. Input harga per item, barcode ISBN, pencarian judul cepat, dan stok buku bekas selalu akurat.',
    keywords: ['aplikasi toko buku bekas', 'software kasir buku second', 'sistem manajemen toko buku bekas', 'pos toko buku bekas', 'kasir toko buku second'],
  },
  {
    slug: 'toko-vinyl',
    name: 'Toko Vinyl & Kaset Musik',
    icon: '🎵',
    painPoint: 'Koleksi vinyl dan kaset langka susah dicatat kondisi dan harganya, sering salah jual.',
    solution: 'Katalog digital per kondisi (mint, VG, G), harga per item fleksibel, dan database koleksi.',
    imageAlt: 'Sistem kasir toko vinyl dan kaset musik koleksi',
    metaDescription: 'Kelola toko vinyl & kaset musik dengan BisnisRapi. Katalog per kondisi, harga fleksibel per item, dan database koleksi musik terlengkap.',
    keywords: ['aplikasi toko vinyl', 'software kasir toko kaset', 'sistem manajemen toko vinyl', 'pos toko vinyl', 'kasir toko musik koleksi'],
  },
  {
    slug: 'toko-craft',
    name: 'Toko Craft & DIY',
    icon: '🧶',
    painPoint: 'Bahan craft dijual per meter, per lembar, dan per gram, bikin kasir bingung hitung harga.',
    solution: 'Multi-satuan fleksibel (meter, lembar, gram) dengan kalkulasi harga otomatis di kasir.',
    imageAlt: 'Sistem kasir toko craft dan DIY dengan multi-satuan',
    metaDescription: 'Kelola toko craft & DIY dengan BisnisRapi. Multi-satuan meter, lembar, gram otomatis, stok bahan craft terkontrol, dan kasir yang mudah dipakai.',
    keywords: ['aplikasi toko craft', 'software kasir toko DIY', 'sistem manajemen toko craft', 'pos toko craft', 'kasir toko kerajinan'],
  },
  {
    slug: 'toko-batik',
    name: 'Toko Batik & Kain Tradisional',
    icon: '🪡',
    painPoint: 'Kain batik punya motif dan ukuran berbeda, susah ngatur stok dan harga tiap lembar.',
    solution: 'Katalog digital per motif dan ukuran kain, harga per lembar fleksibel, dan laporan stok.',
    imageAlt: 'Sistem kasir toko batik dan kain tradisional Indonesia',
    metaDescription: 'Kelola toko batik & kain tradisional dengan BisnisRapi. Katalog per motif & ukuran, harga fleksibel, dan stok kain batik selalu terkontrol.',
    keywords: ['software toko batik', 'aplikasi kasir toko kain', 'sistem manajemen toko batik', 'pos toko batik', 'kasir toko kain tradisional'],
  },
  {
    slug: 'toko-wedding',
    name: 'Wedding Organizer & Dekorasi',
    icon: '💒',
    painPoint: 'Banyak vendor dan item dekorasi yang harus dikoordinasi, sering ada yang kelewat atau dobel.',
    solution: 'Manajemen paket wedding, checklist vendor, invoice klien, dan tracking pembayaran DP.',
    imageAlt: 'Sistem manajemen wedding organizer dan dekorasi pernikahan',
    metaDescription: 'Kelola wedding organizer & dekorasi dengan BisnisRapi. Manajemen paket, checklist vendor, invoice klien, dan tracking DP pernikahan otomatis.',
    keywords: ['software wedding organizer', 'aplikasi manajemen WO', 'sistem kasir dekorasi pernikahan', 'pos wedding organizer', 'aplikasi wedding planner'],
  },
  {
    slug: 'event-organizer',
    name: 'Event Organizer',
    icon: '🎪',
    painPoint: 'Banyak klien dan event berjalan bersamaan, susah ngontrol budget dan pembayaran vendor.',
    solution: 'Manajemen proyek event, tracking budget per klien, dan laporan laba rugi per event.',
    imageAlt: 'Sistem manajemen event organizer dan pengelolaan acara',
    metaDescription: 'Kelola event organizer lebih profesional dengan BisnisRapi. Manajemen proyek, tracking budget, invoice klien, dan laporan laba per event.',
    keywords: ['software event organizer', 'aplikasi manajemen EO', 'sistem kasir event organizer', 'pos event organizer', 'aplikasi pengelolaan acara'],
  },
  {
    slug: 'jasa-cleaning',
    name: 'Jasa Cleaning Service',
    icon: '🧹',
    painPoint: 'Jadwal tim cleaning sering bentrok, susah ngontrol mana yang sudah dikerjakan atau belum.',
    solution: 'Manajemen jadwal tim, tracking pekerjaan per lokasi, dan invoice klien otomatis.',
    imageAlt: 'Sistem manajemen jasa cleaning service profesional',
    metaDescription: 'Kelola jasa cleaning service dengan BisnisRapi. Jadwal tim digital, tracking pekerjaan per lokasi, dan invoice klien otomatis setiap bulan.',
    keywords: ['software cleaning service', 'aplikasi manajemen cleaning', 'sistem jadwal cleaning service', 'pos jasa cleaning', 'aplikasi cleaning service indonesia'],
  },
  {
    slug: 'jasa-catering-box',
    name: 'Jasa Catering Nasi Box',
    icon: '🥡',
    painPoint: 'Order nasi box datang mendadak, susah ngitung kebutuhan bahan dan biaya produksi per box.',
    solution: 'Kalkulator HPP per box otomatis, manajemen order harian, dan laporan laba katering.',
    imageAlt: 'Sistem manajemen order jasa catering nasi box',
    metaDescription: 'Kelola jasa catering nasi box dengan BisnisRapi. HPP per box otomatis, manajemen order harian, dan laporan laba katering yang akurat.',
    keywords: ['software catering nasi box', 'aplikasi manajemen catering', 'sistem order nasi box', 'pos catering', 'aplikasi catering nasi box indonesia'],
  },
  {
    slug: 'jasa-desain',
    name: 'Jasa Desain Grafis & Kreatif',
    icon: '🖌️',
    painPoint: 'Banyak proyek berjalan bersamaan, susah ngontrol progress, revisi, dan tagihan klien.',
    solution: 'Manajemen proyek desain, tracking revisi, invoice klien, dan laporan pendapatan per proyek.',
    imageAlt: 'Sistem manajemen proyek jasa desain grafis dan kreatif',
    metaDescription: 'Kelola jasa desain grafis dengan BisnisRapi. Manajemen proyek, tracking revisi, invoice klien profesional, dan laporan pendapatan kreatif.',
    keywords: ['software jasa desain grafis', 'aplikasi manajemen studio desain', 'sistem invoice desain grafis', 'pos jasa kreatif', 'aplikasi desain grafis indonesia'],
  },
  {
    slug: 'jasa-servis-ac',
    name: 'Jasa Servis AC & Elektronik',
    icon: '❄️',
    painPoint: 'Teknisi di lapangan susah dicatat pekerjaannya, sering lupa tagih ongkos servis ke pelanggan.',
    solution: 'Manajemen order servis per teknisi, invoice digital, dan reminder tagihan pelanggan otomatis.',
    imageAlt: 'Sistem manajemen jasa servis AC dan elektronik',
    metaDescription: 'Kelola jasa servis AC & elektronik dengan BisnisRapi. Order per teknisi, invoice digital, dan reminder tagihan pelanggan otomatis.',
    keywords: ['software jasa servis AC', 'aplikasi manajemen servis elektronik', 'sistem kasir servis AC', 'pos jasa servis', 'aplikasi servis AC indonesia'],
  },
  {
    slug: 'jasa-konstruksi',
    name: 'Kontraktor & Jasa Konstruksi',
    icon: '🏚️',
    painPoint: 'Biaya proyek konstruksi sering membengkak karena nggak ada kontrol pengeluaran material.',
    solution: 'Manajemen RAB proyek, tracking pengeluaran material, dan laporan laba rugi per proyek.',
    imageAlt: 'Sistem manajemen proyek kontraktor dan jasa konstruksi',
    metaDescription: 'Kelola kontraktor & jasa konstruksi dengan BisnisRapi. Manajemen RAB, tracking pengeluaran material, dan laporan laba rugi per proyek bangunan.',
    keywords: ['software kontraktor', 'aplikasi manajemen konstruksi', 'sistem RAB proyek', 'pos jasa konstruksi', 'aplikasi kontraktor indonesia'],
  },
  {
    slug: 'jasa-arsitek',
    name: 'Jasa Arsitek & Interior',
    icon: '🏛️',
    painPoint: 'Proyek desain berjalan lama, susah ngontrol progress dan tagihan termin ke klien.',
    solution: 'Manajemen proyek per fase, invoice termin otomatis, dan laporan pendapatan per klien.',
    imageAlt: 'Sistem manajemen proyek jasa arsitek dan desain interior',
    metaDescription: 'Kelola jasa arsitek & interior dengan BisnisRapi. Manajemen proyek per fase, invoice termin, dan laporan pendapatan desain interior profesional.',
    keywords: ['software jasa arsitek', 'aplikasi manajemen desain interior', 'sistem invoice arsitek', 'pos jasa arsitek', 'aplikasi arsitek indonesia'],
  },
  {
    slug: 'jasa-fotografi',
    name: 'Jasa Fotografi & Videografi',
    icon: '🎬',
    painPoint: 'Jadwal pemotretan sering bentrok, DP belum lunas tapi sudah dikerjakan.',
    solution: 'Kalender booking, tracking DP & pelunasan, dan invoice paket foto/video otomatis.',
    imageAlt: 'Sistem manajemen booking jasa fotografi dan videografi',
    metaDescription: 'Kelola jasa fotografi & videografi dengan BisnisRapi. Booking kalender, tracking DP & pelunasan, dan invoice paket foto video profesional.',
    keywords: ['software jasa fotografi', 'aplikasi manajemen videografi', 'sistem booking fotografer', 'pos jasa fotografi', 'aplikasi fotografer indonesia'],
  },
  {
    slug: 'jasa-wedding-photo',
    name: 'Jasa Foto & Video Pernikahan',
    icon: '💑',
    painPoint: 'Banyak paket wedding photo dengan harga berbeda, susah ngontrol mana yang sudah lunas.',
    solution: 'Manajemen paket wedding, tracking pembayaran termin, dan reminder jadwal pemotretan.',
    imageAlt: 'Sistem manajemen jasa foto dan video pernikahan',
    metaDescription: 'Kelola jasa foto & video pernikahan dengan BisnisRapi. Manajemen paket wedding, tracking termin pembayaran, dan reminder jadwal pemotretan.',
    keywords: ['software jasa foto pernikahan', 'aplikasi manajemen wedding photo', 'sistem booking foto wedding', 'pos jasa wedding photo', 'aplikasi fotografer pernikahan'],
  },
  {
    slug: 'jasa-les-musik',
    name: 'Sekolah Musik & Studio Rekaman',
    icon: '🎹',
    painPoint: 'Jadwal les siswa dan booking studio rekaman sering tabrakan, SPP sering telat dibayar.',
    solution: 'Kalender jadwal les & studio, tagihan SPP otomatis, dan absensi siswa digital.',
    imageAlt: 'Sistem manajemen sekolah musik dan studio rekaman',
    metaDescription: 'Kelola sekolah musik & studio rekaman dengan BisnisRapi. Jadwal les digital, tagihan SPP otomatis, dan booking studio rekaman terkontrol.',
    keywords: ['software sekolah musik', 'aplikasi manajemen studio rekaman', 'sistem jadwal les musik', 'pos sekolah musik', 'aplikasi studio rekaman indonesia'],
  },
  {
    slug: 'jasa-cuci-motor',
    name: 'Jasa Cuci Motor Keliling',
    icon: '🛵',
    painPoint: 'Susah ngitung pendapatan harian karena semua transaksi dicatat di kertas yang gampang hilang.',
    solution: 'Kasir mobile sederhana via HP, laporan pendapatan harian otomatis, dan rekap pelanggan.',
    imageAlt: 'Aplikasi kasir mobile untuk jasa cuci motor keliling',
    metaDescription: 'Kelola jasa cuci motor keliling dengan BisnisRapi. Kasir mobile via HP, laporan pendapatan harian otomatis, dan rekap pelanggan setia.',
    keywords: ['aplikasi cuci motor keliling', 'software kasir cuci motor', 'sistem manajemen cuci motor', 'pos cuci motor', 'kasir jasa cuci motor'],
  },
  {
    slug: 'jasa-pijat',
    name: 'Jasa Pijat & Refleksi',
    icon: '💆',
    painPoint: 'Jadwal terapis sering bentrok, susah ngitung komisi per sesi dan pendapatan harian.',
    solution: 'Booking jadwal terapis, hitung komisi per sesi otomatis, dan laporan pendapatan harian.',
    imageAlt: 'Sistem manajemen booking jasa pijat dan refleksi',
    metaDescription: 'Kelola jasa pijat & refleksi dengan BisnisRapi. Booking jadwal terapis, komisi per sesi otomatis, dan laporan pendapatan harian akurat.',
    keywords: ['software jasa pijat', 'aplikasi manajemen pijat refleksi', 'sistem booking terapis', 'pos jasa pijat', 'kasir jasa pijat indonesia'],
  },
  {
    slug: 'spa-wellness',
    name: 'Spa & Wellness Center',
    icon: '🧖',
    painPoint: 'Banyak paket treatment spa, susah ngontrol stok bahan dan komisi terapis per tindakan.',
    solution: 'Manajemen paket treatment, pemotongan stok bahan otomatis, dan rekap komisi terapis.',
    imageAlt: 'Sistem manajemen spa dan wellness center',
    metaDescription: 'Kelola spa & wellness center dengan BisnisRapi. Manajemen paket treatment, stok bahan otomatis, dan komisi terapis terhitung akurat.',
    keywords: ['software spa', 'aplikasi manajemen wellness center', 'sistem kasir spa', 'pos spa indonesia', 'kasir spa dan wellness'],
  },
  {
    slug: 'klinik-fisioterapi',
    name: 'Klinik Fisioterapi & Rehabilitasi',
    icon: '🏥',
    painPoint: 'Jadwal sesi fisioterapi pasien sering kacau, rekam medis dan progress terapi susah dipantau.',
    solution: 'Jadwal sesi digital, rekam medis per pasien, dan tracking progress rehabilitasi terintegrasi.',
    imageAlt: 'Sistem manajemen klinik fisioterapi dan rehabilitasi',
    metaDescription: 'Kelola klinik fisioterapi & rehabilitasi dengan BisnisRapi. Jadwal sesi digital, rekam medis pasien, dan tracking progress terapi terpantau.',
    keywords: ['software klinik fisioterapi', 'aplikasi manajemen fisioterapi', 'sistem rekam medis fisioterapi', 'pos klinik fisioterapi', 'aplikasi fisioterapi indonesia'],
  },
  {
    slug: 'klinik-umum',
    name: 'Klinik Dokter Umum',
    icon: '🩺',
    painPoint: 'Antrean pasien panjang, rekam medis manual, dan tagihan tindakan sering salah hitung.',
    solution: 'Antrean digital, rekam medis pasien terdigitalisasi, dan invoice tindakan medis otomatis.',
    imageAlt: 'Sistem manajemen klinik dokter umum dengan rekam medis digital',
    metaDescription: 'Kelola klinik dokter umum dengan BisnisRapi. Antrean digital, rekam medis pasien, dan invoice tindakan medis otomatis untuk klinik profesional.',
    keywords: ['software klinik umum', 'aplikasi manajemen klinik', 'sistem rekam medis klinik', 'pos klinik dokter', 'aplikasi klinik indonesia'],
  },
  {
    slug: 'laboratorium',
    name: 'Laboratorium Klinik & Medis',
    icon: '🔬',
    painPoint: 'Hasil pemeriksaan lab sering terlambat dikirim ke pasien, tagihan pemeriksaan sering salah.',
    solution: 'Manajemen order pemeriksaan, invoice otomatis per paket tes, dan notifikasi hasil ke pasien.',
    imageAlt: 'Sistem manajemen laboratorium klinik dan medis',
    metaDescription: 'Kelola laboratorium klinik & medis dengan BisnisRapi. Order pemeriksaan digital, invoice per paket tes, dan notifikasi hasil lab ke pasien.',
    keywords: ['software laboratorium klinik', 'aplikasi manajemen lab medis', 'sistem kasir laboratorium', 'pos laboratorium', 'aplikasi lab klinik indonesia'],
  },
  {
    slug: 'apotek-online',
    name: 'Apotek Online & Delivery Obat',
    icon: '💉',
    painPoint: 'Order obat online masuk dari berbagai channel, susah ngontrol stok dan status pengiriman.',
    solution: 'Integrasi order multi-channel, manajemen stok real-time, dan tracking pengiriman obat.',
    imageAlt: 'Sistem manajemen apotek online dan delivery obat',
    metaDescription: 'Kelola apotek online & delivery obat dengan BisnisRapi. Integrasi order multi-channel, stok real-time, dan tracking pengiriman obat ke pelanggan.',
    keywords: ['software apotek online', 'aplikasi delivery obat', 'sistem manajemen apotek online', 'pos apotek online', 'aplikasi apotek digital'],
  },
  {
    slug: 'toko-susu',
    name: 'Toko Susu & Nutrisi Bayi',
    icon: '🥛',
    painPoint: 'Susu formula punya tanggal kedaluwarsa, sering lupa cek dan malah jual produk expired.',
    solution: 'Notifikasi expired otomatis, manajemen stok FIFO, dan laporan produk mendekati kedaluwarsa.',
    imageAlt: 'Sistem kasir toko susu dan nutrisi bayi dengan manajemen expired',
    metaDescription: 'Kelola toko susu & nutrisi bayi dengan BisnisRapi. Notifikasi expired otomatis, stok FIFO, dan manajemen produk nutrisi bayi terkontrol.',
    keywords: ['aplikasi toko susu bayi', 'software kasir toko nutrisi', 'sistem manajemen toko susu', 'pos toko susu bayi', 'kasir toko nutrisi bayi'],
  },
  {
    slug: 'toko-snack',
    name: 'Toko Snack & Makanan Ringan',
    icon: '🍿',
    painPoint: 'Banyak produk snack dengan expired date dekat, sering rugi karena nggak sempat didiskon.',
    solution: 'Alert produk mendekati expired, promo clearance otomatis, dan laporan produk fast-moving.',
    imageAlt: 'Sistem kasir toko snack dan makanan ringan',
    metaDescription: 'Kelola toko snack & makanan ringan dengan BisnisRapi. Alert expired otomatis, promo clearance, dan laporan produk terlaris setiap hari.',
    keywords: ['aplikasi toko snack', 'software kasir makanan ringan', 'sistem manajemen toko snack', 'pos toko snack', 'kasir toko camilan'],
  },
  {
    slug: 'toko-kopi-bubuk',
    name: 'Toko Kopi Bubuk & Rempah',
    icon: '☕',
    painPoint: 'Kopi dan rempah dijual per gram dan per ons, susah ngitung stok sisa dan harga jual.',
    solution: 'Multi-satuan gram, ons, kg terintegrasi kasir, HPP per satuan otomatis, dan stok akurat.',
    imageAlt: 'Sistem kasir toko kopi bubuk dan rempah dengan timbangan',
    metaDescription: 'Kelola toko kopi bubuk & rempah dengan BisnisRapi. Multi-satuan gram & kg, HPP otomatis, dan stok kopi serta rempah selalu akurat.',
    keywords: ['aplikasi toko kopi bubuk', 'software kasir toko rempah', 'sistem manajemen toko kopi', 'pos toko kopi bubuk', 'kasir toko rempah indonesia'],
  },
  {
    slug: 'toko-roti',
    name: 'Bakery & Toko Roti',
    icon: '🍞',
    painPoint: 'Roti dan kue punya masa simpan pendek, sering ada sisa produksi yang terbuang sia-sia.',
    solution: 'Manajemen produksi harian, alert sisa produk, dan promo bundling otomatis untuk roti sisa.',
    imageAlt: 'Sistem kasir bakery dan toko roti dengan manajemen produksi',
    metaDescription: 'Kelola bakery & toko roti dengan BisnisRapi. Manajemen produksi harian, alert sisa produk, dan promo bundling otomatis untuk kurangi waste.',
    keywords: ['software bakery', 'aplikasi kasir toko roti', 'sistem manajemen bakery', 'pos toko roti', 'kasir bakery indonesia'],
  },
  {
    slug: 'toko-es-krim',
    name: 'Toko Es Krim & Dessert',
    icon: '🍦',
    painPoint: 'Banyak varian rasa dan topping, susah ngontrol stok bahan dan hitung HPP per porsi.',
    solution: 'Manajemen resep per menu, HPP per porsi otomatis, dan stok bahan dessert terkontrol.',
    imageAlt: 'Sistem kasir toko es krim dan dessert dengan manajemen resep',
    metaDescription: 'Kelola toko es krim & dessert dengan BisnisRapi. Manajemen resep, HPP per porsi otomatis, dan stok bahan dessert selalu terkontrol.',
    keywords: ['aplikasi toko es krim', 'software kasir dessert', 'sistem manajemen toko es krim', 'pos toko dessert', 'kasir toko es krim indonesia'],
  },
  {
    slug: 'toko-minuman',
    name: 'Toko Minuman & Jus Segar',
    icon: '🥤',
    painPoint: 'Bahan buah segar cepat busuk, susah ngontrol stok dan waste bahan minuman tiap hari.',
    solution: 'Manajemen stok bahan segar, alert bahan hampir habis, dan HPP per menu minuman otomatis.',
    imageAlt: 'Sistem kasir toko minuman dan jus segar',
    metaDescription: 'Kelola toko minuman & jus segar dengan BisnisRapi. Stok bahan segar terkontrol, HPP per menu otomatis, dan laporan penjualan minuman harian.',
    keywords: ['aplikasi toko minuman', 'software kasir jus segar', 'sistem manajemen toko minuman', 'pos toko jus', 'kasir toko minuman indonesia'],
  },
  {
    slug: 'toko-seafood',
    name: 'Toko Seafood & Ikan Segar',
    icon: '🦐',
    painPoint: 'Ikan dan seafood segar harus cepat terjual, susah ngontrol stok dan harga yang berubah tiap hari.',
    solution: 'Update harga harian cepat, manajemen stok per jenis seafood, dan alert produk hampir habis.',
    imageAlt: 'Sistem kasir toko seafood dan ikan segar',
    metaDescription: 'Kelola toko seafood & ikan segar dengan BisnisRapi. Update harga harian cepat, stok per jenis seafood terkontrol, dan laporan penjualan akurat.',
    keywords: ['aplikasi toko seafood', 'software kasir ikan segar', 'sistem manajemen toko seafood', 'pos toko ikan', 'kasir toko seafood indonesia'],
  },
  {
    slug: 'toko-sayur',
    name: 'Toko Sayur & Buah Online',
    icon: '🥦',
    painPoint: 'Order sayur online masuk dari WhatsApp dan marketplace, susah ngontrol stok dan ongkir.',
    solution: 'Manajemen order multi-channel, stok sayur real-time, dan kalkulasi ongkir otomatis.',
    imageAlt: 'Sistem manajemen toko sayur dan buah online',
    metaDescription: 'Kelola toko sayur & buah online dengan BisnisRapi. Order multi-channel, stok real-time, dan kalkulasi ongkir otomatis untuk toko sayur digital.',
    keywords: ['aplikasi toko sayur online', 'software kasir sayur buah', 'sistem manajemen toko sayur', 'pos toko sayur online', 'aplikasi jualan sayur online'],
  },
  {
    slug: 'toko-madu',
    name: 'Toko Madu & Produk Lebah',
    icon: '🍯',
    painPoint: 'Produk madu punya banyak varian jenis dan ukuran, sering salah jual atau salah harga.',
    solution: 'Katalog digital per jenis dan ukuran madu, harga per varian terkontrol, dan stok akurat.',
    imageAlt: 'Sistem kasir toko madu dan produk lebah',
    metaDescription: 'Kelola toko madu & produk lebah dengan BisnisRapi. Katalog per jenis & ukuran, harga terkontrol, dan stok produk madu selalu akurat.',
    keywords: ['aplikasi toko madu', 'software kasir toko madu', 'sistem manajemen toko madu', 'pos toko madu', 'kasir toko produk lebah'],
  },
  {
    slug: 'toko-kue',
    name: 'Toko Kue & Pastry',
    icon: '🧁',
    painPoint: 'Order kue custom sering datang mendadak, susah ngatur jadwal produksi dan bahan baku.',
    solution: 'Manajemen pre-order kue custom, kalkulator kebutuhan bahan, dan jadwal produksi digital.',
    imageAlt: 'Sistem manajemen toko kue dan pastry dengan pre-order',
    metaDescription: 'Kelola toko kue & pastry dengan BisnisRapi. Pre-order kue custom, kalkulator bahan otomatis, dan jadwal produksi digital terkontrol.',
    keywords: ['aplikasi toko kue', 'software kasir pastry', 'sistem manajemen toko kue', 'pos toko kue', 'kasir toko pastry indonesia'],
  },
  {
    slug: 'toko-coklat',
    name: 'Toko Coklat & Olahan Kakao',
    icon: '🍫',
    painPoint: 'Coklat punya masa simpan terbatas dan banyak varian, susah ngontrol stok dan expired.',
    solution: 'Alert expired otomatis, manajemen varian produk coklat, dan promo clearance untuk stok lama.',
    imageAlt: 'Sistem kasir toko coklat dan olahan kakao',
    metaDescription: 'Kelola toko coklat & olahan kakao dengan BisnisRapi. Alert expired otomatis, manajemen varian, dan promo clearance untuk produk coklat.',
    keywords: ['aplikasi toko coklat', 'software kasir toko kakao', 'sistem manajemen toko coklat', 'pos toko coklat', 'kasir toko coklat indonesia'],
  },
  {
    slug: 'toko-keripik',
    name: 'Toko Keripik & Camilan Lokal',
    icon: '🥔',
    painPoint: 'Produk camilan lokal punya banyak varian rasa, susah ngontrol stok dan harga tiap varian.',
    solution: 'Manajemen varian rasa per produk, stok per SKU terkontrol, dan laporan produk terlaris.',
    imageAlt: 'Sistem kasir toko keripik dan camilan lokal Indonesia',
    metaDescription: 'Kelola toko keripik & camilan lokal dengan BisnisRapi. Manajemen varian rasa, stok per SKU, dan laporan produk camilan terlaris setiap hari.',
    keywords: ['aplikasi toko keripik', 'software kasir camilan lokal', 'sistem manajemen toko keripik', 'pos toko camilan', 'kasir toko keripik indonesia'],
  },
  {
    slug: 'toko-jamu',
    name: 'Toko Jamu & Minuman Herbal',
    icon: '🌱',
    painPoint: 'Jamu dijual dalam berbagai bentuk (cair, serbuk, kapsul), susah ngontrol stok dan expired.',
    solution: 'Manajemen stok per bentuk produk, alert expired otomatis, dan laporan penjualan jamu.',
    imageAlt: 'Sistem kasir toko jamu dan minuman herbal tradisional',
    metaDescription: 'Kelola toko jamu & minuman herbal dengan BisnisRapi. Stok per bentuk produk, alert expired otomatis, dan laporan penjualan jamu tradisional.',
    keywords: ['aplikasi toko jamu', 'software kasir minuman herbal', 'sistem manajemen toko jamu', 'pos toko jamu', 'kasir toko herbal indonesia'],
  },
  {
    slug: 'toko-air-minum',
    name: 'Depot Air Minum Isi Ulang',
    icon: '💧',
    painPoint: 'Susah ngitung berapa galon yang sudah diisi ulang dan berapa pendapatan harian yang masuk.',
    solution: 'Kasir sederhana per galon, laporan pendapatan harian otomatis, dan rekap pelanggan langganan.',
    imageAlt: 'Sistem kasir depot air minum isi ulang',
    metaDescription: 'Kelola depot air minum isi ulang dengan BisnisRapi. Kasir per galon, laporan pendapatan harian otomatis, dan rekap pelanggan langganan.',
    keywords: ['aplikasi depot air minum', 'software kasir depot galon', 'sistem manajemen depot air', 'pos depot air minum', 'kasir depot air isi ulang'],
  },
  {
    slug: 'toko-gas',
    name: 'Agen Gas LPG & Minyak Tanah',
    icon: '🔥',
    painPoint: 'Stok tabung gas sering nggak sinkron antara fisik dan catatan, banyak tabung hilang.',
    solution: 'Manajemen stok tabung per ukuran (3kg, 12kg), tracking tabung keluar-masuk, dan laporan harian.',
    imageAlt: 'Sistem manajemen agen gas LPG dan minyak tanah',
    metaDescription: 'Kelola agen gas LPG & minyak tanah dengan BisnisRapi. Stok tabung per ukuran, tracking keluar-masuk tabung, dan laporan penjualan harian akurat.',
    keywords: ['aplikasi agen gas LPG', 'software kasir agen gas', 'sistem manajemen agen gas', 'pos agen gas LPG', 'kasir agen gas indonesia'],
  },
];

export function getIndustryBySlug(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug);
}
